export declare const defaultText: string;
export declare const footerText: string;
export declare const heading: string;
export declare const heading1: string;
export declare const heading2: string;
export declare const logo: string;
export declare const socialMedia: string;
export declare const text: string;
export declare const wrapper: string;
